import discord
from discord.ext import commands, tasks
import logging
import random

log = logging.getLogger("jamet")

STATUS_MESSAGES = [
    (discord.ActivityType.playing, "rebuild project e memory leak sing ra ketemu"),
    (discord.ActivityType.watching, "kodinganmu sing koyok taek"),
    (discord.ActivityType.watching, "git log e sing error terus"),
    (discord.ActivityType.watching, "codebase e sing mblenyek"),
    (discord.ActivityType.watching, "database e sing corrupt"),
    (discord.ActivityType.playing, "refactor kode e scope creep sing ra kelar-kelar"),
    (discord.ActivityType.watching, "arsitektur e sing koyok taek"),
    (discord.ActivityType.playing, "debugging requirement sing ganti terus"),
    (discord.ActivityType.watching, "docker container e sing mblenyek"),
    (discord.ActivityType.playing, "game tebak junior developer polos"),
    (discord.ActivityType.listening, "bacotan e soal server yang sering down"),
    (discord.ActivityType.watching, "database e sing mblenyek"),
    (discord.ActivityType.watching, "konfigurasi e sing gak keurus"),
    (discord.ActivityType.watching, "docker container e sing iso opo iki"),
    (discord.ActivityType.playing, "googling error e bug production malam ini"),
    (discord.ActivityType.watching, "query e sing ngadat"),
    (discord.ActivityType.watching, "arsitektur e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.watching, "frontend e sing modyar"),
    (discord.ActivityType.playing, "rebuild project e requirement sing ganti terus"),
    (discord.ActivityType.listening, "celotehan e sing ra ono entek'e"),
    (discord.ActivityType.watching, "codebase e sing modyar"),
    (discord.ActivityType.watching, "log e sing amblas"),
    (discord.ActivityType.watching, "API e sing njebrot"),
    (discord.ActivityType.watching, "frontend e sing gak keurus"),
    (discord.ActivityType.playing, "deploy gagal e deadline besok"),
    (discord.ActivityType.watching, "konfigurasi e sing iso opo iki"),
    (discord.ActivityType.watching, "log e sing error terus"),
    (discord.ActivityType.watching, "git log e sing modyar"),
    (discord.ActivityType.listening, "curhatan developer e soal code review yang kejam"),
    (discord.ActivityType.watching, "kodinganmu sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.listening, "omelan client e soal testing yang ga kelar"),
    (discord.ActivityType.playing, "mikirin solusi buat deadline besok"),
    (discord.ActivityType.listening, "curhat e soal fitur yang ga pernah jadi"),
    (discord.ActivityType.listening, "celotehan e soal deploy yang gagal terus"),
    (discord.ActivityType.watching, "vps e sing koyok taek"),
    (discord.ActivityType.watching, "git log e sing iso opo iki"),
    (discord.ActivityType.watching, "bug e sing ra iso jalan"),
    (discord.ActivityType.listening, "keluhan e soal code review yang kejam"),
    (discord.ActivityType.watching, "arsitektur e sing bosok"),
    (discord.ActivityType.playing, "deploy gagal e requirement sing ganti terus"),
    (discord.ActivityType.watching, "kode spaghetti e sing nangis"),
    (discord.ActivityType.listening, "ocehan e soal fitur yang ga pernah jadi"),
    (discord.ActivityType.watching, "database e sing nangis"),
    (discord.ActivityType.watching, "bug e sing mblenyek"),
    (discord.ActivityType.watching, "frontend e sing error terus"),
    (discord.ActivityType.listening, "keluhan e soal deadline besok"),
    (discord.ActivityType.watching, "konfigurasi e sing koyok taek"),
    (discord.ActivityType.watching, "backend e sing mlumpat"),
    (discord.ActivityType.listening, "ocehan e soal bug sing ra iso fix"),
    (discord.ActivityType.watching, "frontend e sing koyok taek"),
    (discord.ActivityType.watching, "backend e sing kepanasan"),
    (discord.ActivityType.watching, "backend e sing njebrot"),
    (discord.ActivityType.playing, "simulator ngadepin error 500 sing ra ono sebab e"),
    (discord.ActivityType.watching, "API e sing iso opo iki"),
    (discord.ActivityType.listening, "ocehan e soal deadline besok"),
    (discord.ActivityType.watching, "backend e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.listening, "keluhan e soal testing yang ga kelar"),
    (discord.ActivityType.watching, "query e sing error terus"),
    (discord.ActivityType.listening, "bacotan e soal code review yang kejam"),
    (discord.ActivityType.playing, "permainan kesabaran scope creep sing ra kelar-kelar"),
    (discord.ActivityType.watching, "kode spaghetti e sing ra iso jalan"),
    (discord.ActivityType.watching, "server e sing bosok"),
    (discord.ActivityType.playing, "nyobo mbenerke scope creep sing ra kelar-kelar"),
    (discord.ActivityType.watching, "docker container e sing ajaib kok iso jalan"),
    (discord.ActivityType.listening, "komplen e soal fitur yang ga pernah jadi"),
    (discord.ActivityType.listening, "keluhan e soal fitur yang ga pernah jadi"),
    (discord.ActivityType.playing, "permainan kesabaran deadline besok"),
    (discord.ActivityType.watching, "query e sing kepanasan"),
    (discord.ActivityType.listening, "curhat e soal server yang sering down"),
    (discord.ActivityType.playing, "nyobo mbenerke deadline besok"),
    (discord.ActivityType.watching, "environment variable e sing ajaib kok iso jalan"),
    (discord.ActivityType.watching, "frontend e sing iso opo iki"),
    (discord.ActivityType.watching, "query e sing mblenyek"),
    (discord.ActivityType.watching, "arsitektur e sing gak keurus"),
    (discord.ActivityType.watching, "konfigurasi e sing ra iso jalan"),
    (discord.ActivityType.watching, "frontend e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.playing, "mikirin solusi buat client ra karuan"),
    (discord.ActivityType.listening, "omelan client e soal fitur yang ga pernah jadi"),
    (discord.ActivityType.listening, "bacotan e soal deploy yang gagal terus"),
    (discord.ActivityType.watching, "pipeline e sing modyar"),
    (discord.ActivityType.playing, "simulator ngadepin kode warisan jaman dinosaurus"),
    (discord.ActivityType.listening, "ngeyele soal fitur yang ga pernah jadi"),
    (discord.ActivityType.playing, "game tebak bug production malam ini"),
    (discord.ActivityType.watching, "konfigurasi e sing mlumpat"),
    (discord.ActivityType.playing, "nyobo mbenerke client ra karuan"),
    (discord.ActivityType.playing, "rebuild project e bug production malam ini"),
    (discord.ActivityType.watching, "arsitektur e sing mblenyek"),
    (discord.ActivityType.watching, "konfigurasi e sing njebrot"),
    (discord.ActivityType.watching, "konfigurasi e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.watching, "log e sing bosok"),
    (discord.ActivityType.watching, "query e sing corrupt"),
    (discord.ActivityType.playing, "mikirin solusi buat user pekok"),
    (discord.ActivityType.watching, "codebase e sing iso opo iki"),
    (discord.ActivityType.watching, "API e sing bosok"),
    (discord.ActivityType.watching, "frontend e sing mlumpat"),
    (discord.ActivityType.watching, "log e sing ra iso jalan"),
    (discord.ActivityType.watching, "database e sing error terus"),
    (discord.ActivityType.watching, "bug e sing error terus"),
    (discord.ActivityType.watching, "git log e sing kepanasan"),
    (discord.ActivityType.watching, "frontend e sing kepanasan"),
    (discord.ActivityType.watching, "git log e sing koyok taek"),
    (discord.ActivityType.watching, "database e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.watching, "docker container e sing corrupt"),
    (discord.ActivityType.watching, "API e sing gak keurus"),
    (discord.ActivityType.watching, "kodinganmu sing gak keurus"),
    (discord.ActivityType.playing, "rebuild project e error 500 sing ra ono sebab e"),
    (discord.ActivityType.watching, "vps e sing kepanasan"),
    (discord.ActivityType.playing, "permainan kesabaran user pekok"),
    (discord.ActivityType.watching, "log e sing gak keurus"),
    (discord.ActivityType.watching, "git log e sing ajaib kok iso jalan"),
    (discord.ActivityType.watching, "server e sing ra iso jalan"),
    (discord.ActivityType.watching, "database e sing gak keurus"),
    (discord.ActivityType.listening, "sambatmu soal deploy yang gagal terus"),
    (discord.ActivityType.watching, "docker container e sing njebrot"),
    (discord.ActivityType.playing, "game tebak scope creep sing ra kelar-kelar"),
    (discord.ActivityType.playing, "mikirin solusi buat junior developer polos"),
    (discord.ActivityType.listening, "bacotan e soal deadline besok"),
    (discord.ActivityType.watching, "codebase e sing ra iso jalan"),
    (discord.ActivityType.playing, "refactor kode e error 500 sing ra ono sebab e"),
    (discord.ActivityType.watching, "codebase e sing nangis"),
    (discord.ActivityType.watching, "query e sing nangis"),
    (discord.ActivityType.watching, "bug e sing ajaib kok iso jalan"),
    (discord.ActivityType.watching, "codebase e sing bosok"),
    (discord.ActivityType.watching, "log e sing nangis"),
    (discord.ActivityType.playing, "debugging user pekok"),
    (discord.ActivityType.watching, "vps e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.watching, "docker container e sing koyok taek"),
    (discord.ActivityType.playing, "nyobo mbenerke error 500 sing ra ono sebab e"),
    (discord.ActivityType.playing, "debugging deadline besok"),
    (discord.ActivityType.watching, "pipeline e sing kepanasan"),
    (discord.ActivityType.listening, "tangisan e soal gaji yang belum naik"),
    (discord.ActivityType.watching, "git log e sing ra iso jalan"),
    (discord.ActivityType.playing, "permainan kesabaran kode warisan jaman dinosaurus"),
    (discord.ActivityType.playing, "nyobo mbenerke junior developer polos"),
    (discord.ActivityType.watching, "environment variable e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.watching, "git log e sing amblas"),
    (discord.ActivityType.listening, "celotehan e soal bug sing ra iso fix"),
    (discord.ActivityType.watching, "environment variable e sing koyok taek"),
    (discord.ActivityType.listening, "ngeyele soal server yang sering down"),
    (discord.ActivityType.listening, "komplen e soal server yang sering down"),
    (discord.ActivityType.watching, "codebase e sing ajaib kok iso jalan"),
    (discord.ActivityType.watching, "environment variable e sing kepanasan"),
    (discord.ActivityType.watching, "arsitektur e sing amblas"),
    (discord.ActivityType.watching, "bug e sing bosok"),
    (discord.ActivityType.playing, "deploy gagal e kode warisan jaman dinosaurus"),
    (discord.ActivityType.playing, "nyobo mbenerke memory leak sing ra ketemu"),
    (discord.ActivityType.listening, "omelan client e soal deploy yang gagal terus"),
    (discord.ActivityType.listening, "curhat e soal gaji yang belum naik"),
    (discord.ActivityType.watching, "arsitektur e sing kepanasan"),
    (discord.ActivityType.watching, "kode spaghetti e sing kepanasan"),
    (discord.ActivityType.listening, "curhat e soal bug sing ra iso fix"),
    (discord.ActivityType.watching, "server e sing error terus"),
    (discord.ActivityType.watching, "log e sing ajaib kok iso jalan"),
    (discord.ActivityType.watching, "database e sing koyok taek"),
    (discord.ActivityType.watching, "kode spaghetti e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.playing, "deploy gagal e memory leak sing ra ketemu"),
    (discord.ActivityType.watching, "kodinganmu sing njebrot"),
    (discord.ActivityType.watching, "server e sing mlumpat"),
    (discord.ActivityType.watching, "vps e sing ngadat"),
    (discord.ActivityType.playing, "debugging bug production malam ini"),
    (discord.ActivityType.playing, "deploy gagal e user pekok"),
    (discord.ActivityType.listening, "sambatmu soal deadline besok"),
    (discord.ActivityType.watching, "codebase e sing kepanasan"),
    (discord.ActivityType.watching, "API e sing amblas"),
    (discord.ActivityType.watching, "log e sing corrupt"),
    (discord.ActivityType.watching, "bug e sing nangis"),
    (discord.ActivityType.watching, "kode spaghetti e sing corrupt"),
    (discord.ActivityType.watching, "kode spaghetti e sing gak keurus"),
    (discord.ActivityType.playing, "game tebak error 500 sing ra ono sebab e"),
    (discord.ActivityType.watching, "pipeline e sing njebrot"),
    (discord.ActivityType.listening, "omelan client e soal bug sing ra iso fix"),
    (discord.ActivityType.watching, "API e sing ra iso jalan"),
    (discord.ActivityType.watching, "vps e sing mlumpat"),
    (discord.ActivityType.listening, "ocehan e soal deploy yang gagal terus"),
    (discord.ActivityType.watching, "kodinganmu sing modyar"),
    (discord.ActivityType.listening, "bacotan e sing ra ono entek'e"),
    (discord.ActivityType.playing, "deploy gagal e client ra karuan"),
    (discord.ActivityType.playing, "simulator ngadepin bug production malam ini"),
    (discord.ActivityType.watching, "kodinganmu sing mblenyek"),
    (discord.ActivityType.watching, "backend e sing ra iso jalan"),
    (discord.ActivityType.playing, "game tebak requirement sing ganti terus"),
    (discord.ActivityType.listening, "ocehan e soal project manager sing mbulet"),
    (discord.ActivityType.watching, "arsitektur e sing error terus"),
    (discord.ActivityType.watching, "backend e sing ajaib kok iso jalan"),
    (discord.ActivityType.playing, "permainan kesabaran memory leak sing ra ketemu"),
    (discord.ActivityType.watching, "log e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.watching, "backend e sing gak keurus"),
    (discord.ActivityType.watching, "backend e sing error terus"),
    (discord.ActivityType.listening, "curhatan developer e soal deadline besok"),
    (discord.ActivityType.listening, "curhat e soal project manager sing mbulet"),
    (discord.ActivityType.playing, "game tebak user pekok"),
    (discord.ActivityType.listening, "sambatmu soal code review yang kejam"),
    (discord.ActivityType.listening, "ocehan e sing ra ono entek'e"),
    (discord.ActivityType.watching, "server e sing njebrot"),
    (discord.ActivityType.watching, "pipeline e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.playing, "nyobo mbenerke user pekok"),
    (discord.ActivityType.watching, "kodinganmu sing ajaib kok iso jalan"),
    (discord.ActivityType.watching, "server e sing ajaib kok iso jalan"),
    (discord.ActivityType.listening, "celotehan e soal code review yang kejam"),
    (discord.ActivityType.playing, "refactor kode e user pekok"),
    (discord.ActivityType.playing, "nyobo mbenerke requirement sing ganti terus"),
    (discord.ActivityType.watching, "vps e sing ajaib kok iso jalan"),
    (discord.ActivityType.watching, "konfigurasi e sing kepanasan"),
    (discord.ActivityType.listening, "curhat e soal deadline besok"),
    (discord.ActivityType.listening, "bacotan e soal testing yang ga kelar"),
    (discord.ActivityType.watching, "kode spaghetti e sing ngadat"),
    (discord.ActivityType.watching, "konfigurasi e sing ajaib kok iso jalan"),
    (discord.ActivityType.watching, "kode spaghetti e sing iso opo iki"),
    (discord.ActivityType.watching, "vps e sing amblas"),
    (discord.ActivityType.listening, "sambatmu sing ra ono entek'e"),
    (discord.ActivityType.playing, "rebuild project e user pekok"),
    (discord.ActivityType.listening, "komplen e soal deadline besok"),
    (discord.ActivityType.watching, "frontend e sing amblas"),
    (discord.ActivityType.watching, "pipeline e sing ra iso jalan"),
    (discord.ActivityType.listening, "tangisan e soal testing yang ga kelar"),
    (discord.ActivityType.watching, "backend e sing ngadat"),
    (discord.ActivityType.watching, "codebase e sing gak keurus"),
    (discord.ActivityType.playing, "mikirin solusi buat memory leak sing ra ketemu"),
    (discord.ActivityType.watching, "server e sing koyok taek"),
    (discord.ActivityType.playing, "rebuild project e stack overflow sing koyok kitab suci"),
    (discord.ActivityType.listening, "ngeyele soal testing yang ga kelar"),
    (discord.ActivityType.watching, "API e sing error terus"),
    (discord.ActivityType.watching, "backend e sing corrupt"),
    (discord.ActivityType.playing, "mikirin solusi buat scope creep sing ra kelar-kelar"),
    (discord.ActivityType.watching, "log e sing koyok taek"),
    (discord.ActivityType.watching, "vps e sing corrupt"),
    (discord.ActivityType.playing, "permainan kesabaran junior developer polos"),
    (discord.ActivityType.watching, "bug e sing ngadat"),
    (discord.ActivityType.watching, "query e sing ra iso jalan"),
    (discord.ActivityType.watching, "frontend e sing ngadat"),
    (discord.ActivityType.watching, "environment variable e sing modyar"),
    (discord.ActivityType.watching, "codebase e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.playing, "simulator ngadepin junior developer polos"),
    (discord.ActivityType.watching, "environment variable e sing ra iso jalan"),
    (discord.ActivityType.watching, "bug e sing amblas"),
    (discord.ActivityType.watching, "backend e sing amblas"),
    (discord.ActivityType.listening, "keluhan e soal project manager sing mbulet"),
    (discord.ActivityType.watching, "pipeline e sing gak keurus"),
    (discord.ActivityType.listening, "komplen e soal gaji yang belum naik"),
    (discord.ActivityType.watching, "backend e sing bosok"),
    (discord.ActivityType.watching, "environment variable e sing corrupt"),
    (discord.ActivityType.listening, "keluhan e sing ra ono entek'e"),
    (discord.ActivityType.listening, "ngeyele soal deploy yang gagal terus"),
    (discord.ActivityType.playing, "googling error e junior developer polos"),
    (discord.ActivityType.playing, "game tebak memory leak sing ra ketemu"),
    (discord.ActivityType.listening, "ngeyele sing ra ono entek'e"),
    (discord.ActivityType.watching, "codebase e sing njebrot"),
    (discord.ActivityType.watching, "environment variable e sing mlumpat"),
    (discord.ActivityType.watching, "docker container e sing bosok"),
    (discord.ActivityType.playing, "mainin bug production malam ini"),
    (discord.ActivityType.watching, "backend e sing iso opo iki"),
    (discord.ActivityType.playing, "rebuild project e deadline besok"),
    (discord.ActivityType.watching, "arsitektur e sing ra iso jalan"),
    (discord.ActivityType.playing, "deploy gagal e scope creep sing ra kelar-kelar"),
    (discord.ActivityType.watching, "API e sing ngadat"),
    (discord.ActivityType.playing, "googling error e deadline besok"),
    (discord.ActivityType.playing, "simulator ngadepin user pekok"),
    (discord.ActivityType.watching, "codebase e sing corrupt"),
    (discord.ActivityType.listening, "ocehan e soal testing yang ga kelar"),
    (discord.ActivityType.playing, "googling error e user pekok"),
    (discord.ActivityType.listening, "bacotan e soal bug sing ra iso fix"),
    (discord.ActivityType.watching, "vps e sing bosok"),
    (discord.ActivityType.watching, "environment variable e sing mblenyek"),
    (discord.ActivityType.playing, "refactor kode e memory leak sing ra ketemu"),
    (discord.ActivityType.watching, "arsitektur e sing nangis"),
    (discord.ActivityType.listening, "sambatmu soal server yang sering down"),
    (discord.ActivityType.listening, "tangisan e soal fitur yang ga pernah jadi"),
    (discord.ActivityType.watching, "bug e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.watching, "environment variable e sing amblas"),
    (discord.ActivityType.playing, "mainin error 500 sing ra ono sebab e"),
    (discord.ActivityType.watching, "git log e sing mblenyek"),
    (discord.ActivityType.playing, "refactor kode e deadline besok"),
    (discord.ActivityType.playing, "nyobo mbenerke stack overflow sing koyok kitab suci"),
    (discord.ActivityType.watching, "API e sing modyar"),
    (discord.ActivityType.watching, "bug e sing koyok taek"),
    (discord.ActivityType.playing, "permainan kesabaran error 500 sing ra ono sebab e"),
    (discord.ActivityType.playing, "refactor kode e client ra karuan"),
    (discord.ActivityType.watching, "arsitektur e sing ajaib kok iso jalan"),
    (discord.ActivityType.playing, "debugging kode warisan jaman dinosaurus"),
    (discord.ActivityType.playing, "debugging scope creep sing ra kelar-kelar"),
    (discord.ActivityType.listening, "sambatmu soal bug sing ra iso fix"),
    (discord.ActivityType.watching, "API e sing ajaib kok iso jalan"),
    (discord.ActivityType.watching, "pipeline e sing nangis"),
    (discord.ActivityType.watching, "bug e sing modyar"),
    (discord.ActivityType.watching, "konfigurasi e sing corrupt"),
    (discord.ActivityType.watching, "konfigurasi e sing amblas"),
    (discord.ActivityType.listening, "celotehan e soal server yang sering down"),
    (discord.ActivityType.watching, "server e sing modyar"),
    (discord.ActivityType.watching, "pipeline e sing error terus"),
    (discord.ActivityType.watching, "query e sing modyar"),
    (discord.ActivityType.watching, "frontend e sing nangis"),
    (discord.ActivityType.watching, "kode spaghetti e sing njebrot"),
    (discord.ActivityType.watching, "server e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.listening, "ngeyele soal gaji yang belum naik"),
    (discord.ActivityType.watching, "arsitektur e sing mlumpat"),
    (discord.ActivityType.playing, "refactor kode e requirement sing ganti terus"),
    (discord.ActivityType.watching, "log e sing ngadat"),
    (discord.ActivityType.watching, "docker container e sing kepanasan"),
    (discord.ActivityType.watching, "kodinganmu sing iso opo iki"),
    (discord.ActivityType.playing, "permainan kesabaran bug production malam ini"),
    (discord.ActivityType.watching, "pipeline e sing iso opo iki"),
    (discord.ActivityType.watching, "query e sing bosok"),
    (discord.ActivityType.playing, "mainin deadline besok"),
    (discord.ActivityType.listening, "celotehan e soal project manager sing mbulet"),
    (discord.ActivityType.playing, "googling error e scope creep sing ra kelar-kelar"),
    (discord.ActivityType.watching, "codebase e sing error terus"),
    (discord.ActivityType.playing, "mainin user pekok"),
    (discord.ActivityType.watching, "log e sing mblenyek"),
    (discord.ActivityType.watching, "database e sing ajaib kok iso jalan"),
    (discord.ActivityType.listening, "ngeyele soal bug sing ra iso fix"),
    (discord.ActivityType.listening, "curhatan developer e soal gaji yang belum naik"),
    (discord.ActivityType.watching, "konfigurasi e sing modyar"),
    (discord.ActivityType.listening, "ngeyele soal deadline besok"),
    (discord.ActivityType.watching, "server e sing iso opo iki"),
    (discord.ActivityType.playing, "refactor kode e bug production malam ini"),
    (discord.ActivityType.listening, "keluhan e soal deploy yang gagal terus"),
    (discord.ActivityType.listening, "sambatmu soal project manager sing mbulet"),
    (discord.ActivityType.watching, "kode spaghetti e sing amblas"),
    (discord.ActivityType.listening, "omelan client e soal code review yang kejam"),
    (discord.ActivityType.playing, "mainin kode warisan jaman dinosaurus"),
    (discord.ActivityType.watching, "vps e sing modyar"),
    (discord.ActivityType.listening, "curhat e soal testing yang ga kelar"),
    (discord.ActivityType.watching, "log e sing iso opo iki"),
    (discord.ActivityType.watching, "query e sing amblas"),
    (discord.ActivityType.listening, "tangisan e soal code review yang kejam"),
    (discord.ActivityType.watching, "environment variable e sing error terus"),
    (discord.ActivityType.playing, "nyobo mbenerke kode warisan jaman dinosaurus"),
    (discord.ActivityType.listening, "omelan client e soal deadline besok"),
    (discord.ActivityType.listening, "bacotan e soal fitur yang ga pernah jadi"),
    (discord.ActivityType.watching, "bug e sing gak keurus"),
    (discord.ActivityType.playing, "mikirin solusi buat requirement sing ganti terus"),
    (discord.ActivityType.playing, "simulator ngadepin deadline besok"),
    (discord.ActivityType.playing, "nyobo mbenerke bug production malam ini"),
    (discord.ActivityType.listening, "omelan client e soal gaji yang belum naik"),
    (discord.ActivityType.watching, "kode spaghetti e sing mlumpat"),
    (discord.ActivityType.watching, "API e sing mlumpat"),
    (discord.ActivityType.watching, "log e sing mlumpat"),
    (discord.ActivityType.playing, "googling error e error 500 sing ra ono sebab e"),
    (discord.ActivityType.playing, "simulator ngadepin scope creep sing ra kelar-kelar"),
    (discord.ActivityType.listening, "curhatan developer e soal testing yang ga kelar"),
    (discord.ActivityType.watching, "bug e sing njebrot"),
    (discord.ActivityType.listening, "ngeyele soal code review yang kejam"),
    (discord.ActivityType.playing, "deploy gagal e stack overflow sing koyok kitab suci"),
    (discord.ActivityType.watching, "frontend e sing bosok"),
    (discord.ActivityType.playing, "simulator ngadepin requirement sing ganti terus"),
    (discord.ActivityType.playing, "mainin junior developer polos"),
    (discord.ActivityType.watching, "vps e sing ra iso jalan"),
    (discord.ActivityType.watching, "pipeline e sing bosok"),
    (discord.ActivityType.listening, "komplen e sing ra ono entek'e"),
    (discord.ActivityType.watching, "query e sing njebrot"),
    (discord.ActivityType.watching, "docker container e sing ngadat"),
    (discord.ActivityType.watching, "vps e sing error terus"),
    (discord.ActivityType.watching, "arsitektur e sing modyar"),
    (discord.ActivityType.listening, "tangisan e sing ra ono entek'e"),
    (discord.ActivityType.watching, "pipeline e sing ngadat"),
    (discord.ActivityType.playing, "mainin client ra karuan"),
    (discord.ActivityType.playing, "mikirin solusi buat error 500 sing ra ono sebab e"),
    (discord.ActivityType.watching, "pipeline e sing mblenyek"),
    (discord.ActivityType.listening, "ocehan e soal gaji yang belum naik"),
    (discord.ActivityType.watching, "backend e sing mblenyek"),
    (discord.ActivityType.listening, "komplen e soal testing yang ga kelar"),
    (discord.ActivityType.playing, "googling error e requirement sing ganti terus"),
    (discord.ActivityType.watching, "log e sing modyar"),
    (discord.ActivityType.watching, "frontend e sing ajaib kok iso jalan"),
    (discord.ActivityType.watching, "query e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.playing, "simulator ngadepin stack overflow sing koyok kitab suci"),
    (discord.ActivityType.watching, "pipeline e sing ajaib kok iso jalan"),
    (discord.ActivityType.playing, "rebuild project e junior developer polos"),
    (discord.ActivityType.watching, "codebase e sing mlumpat"),
    (discord.ActivityType.watching, "frontend e sing njebrot"),
    (discord.ActivityType.watching, "database e sing modyar"),
    (discord.ActivityType.watching, "database e sing bosok"),
    (discord.ActivityType.watching, "kodinganmu sing kepanasan"),
    (discord.ActivityType.listening, "komplen e soal project manager sing mbulet"),
    (discord.ActivityType.listening, "sambatmu soal fitur yang ga pernah jadi"),
    (discord.ActivityType.listening, "celotehan e soal fitur yang ga pernah jadi"),
    (discord.ActivityType.watching, "konfigurasi e sing mblenyek"),
    (discord.ActivityType.playing, "debugging error 500 sing ra ono sebab e"),
    (discord.ActivityType.listening, "keluhan e soal server yang sering down"),
    (discord.ActivityType.watching, "kodinganmu sing error terus"),
    (discord.ActivityType.listening, "komplen e soal code review yang kejam"),
    (discord.ActivityType.watching, "codebase e sing koyok taek"),
    (discord.ActivityType.playing, "game tebak kode warisan jaman dinosaurus"),
    (discord.ActivityType.watching, "git log e sing ngadat"),
    (discord.ActivityType.watching, "kodinganmu sing amblas"),
    (discord.ActivityType.watching, "server e sing ngadat"),
    (discord.ActivityType.watching, "codebase e sing amblas"),
    (discord.ActivityType.listening, "omelan client e soal project manager sing mbulet"),
    (discord.ActivityType.watching, "vps e sing gak keurus"),
    (discord.ActivityType.watching, "vps e sing nangis"),
    (discord.ActivityType.watching, "docker container e sing ra iso jalan"),
    (discord.ActivityType.watching, "vps e sing mblenyek"),
    (discord.ActivityType.playing, "refactor kode e stack overflow sing koyok kitab suci"),
    (discord.ActivityType.watching, "frontend e sing mblenyek"),
    (discord.ActivityType.playing, "mikirin solusi buat stack overflow sing koyok kitab suci"),
    (discord.ActivityType.watching, "vps e sing iso opo iki"),
    (discord.ActivityType.watching, "docker container e sing error terus"),
    (discord.ActivityType.watching, "bug e sing mlumpat"),
    (discord.ActivityType.watching, "git log e sing corrupt"),
    (discord.ActivityType.playing, "deploy gagal e bug production malam ini"),
    (discord.ActivityType.watching, "git log e sing bosok"),
    (discord.ActivityType.watching, "database e sing ngadat"),
    (discord.ActivityType.listening, "ngeyele soal project manager sing mbulet"),
    (discord.ActivityType.watching, "server e sing gak keurus"),
    (discord.ActivityType.watching, "API e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.watching, "bug e sing kepanasan"),
    (discord.ActivityType.watching, "docker container e sing modyar"),
    (discord.ActivityType.listening, "tangisan e soal project manager sing mbulet"),
    (discord.ActivityType.watching, "kode spaghetti e sing koyok taek"),
    (discord.ActivityType.watching, "git log e sing mlumpat"),
    (discord.ActivityType.watching, "frontend e sing corrupt"),
    (discord.ActivityType.watching, "environment variable e sing iso opo iki"),
    (discord.ActivityType.listening, "sambatmu soal testing yang ga kelar"),
    (discord.ActivityType.listening, "bacotan e soal project manager sing mbulet"),
    (discord.ActivityType.watching, "arsitektur e sing ngadat"),
    (discord.ActivityType.playing, "debugging memory leak sing ra ketemu"),
    (discord.ActivityType.watching, "pipeline e sing koyok taek"),
    (discord.ActivityType.watching, "environment variable e sing bosok"),
    (discord.ActivityType.watching, "environment variable e sing nangis"),
    (discord.ActivityType.listening, "curhatan developer e soal project manager sing mbulet"),
    (discord.ActivityType.listening, "curhatan developer e soal server yang sering down"),
    (discord.ActivityType.watching, "query e sing ajaib kok iso jalan"),
    (discord.ActivityType.listening, "keluhan e soal gaji yang belum naik"),
    (discord.ActivityType.listening, "bacotan e soal gaji yang belum naik"),
    (discord.ActivityType.playing, "debugging stack overflow sing koyok kitab suci"),
    (discord.ActivityType.watching, "API e sing kepanasan"),
    (discord.ActivityType.watching, "database e sing mlumpat"),
    (discord.ActivityType.watching, "vps e sing njebrot"),
    (discord.ActivityType.playing, "debugging junior developer polos"),
    (discord.ActivityType.listening, "tangisan e soal deadline besok"),
    (discord.ActivityType.playing, "googling error e memory leak sing ra ketemu"),
    (discord.ActivityType.playing, "deploy gagal e error 500 sing ra ono sebab e"),
    (discord.ActivityType.listening, "ocehan e soal server yang sering down"),
    (discord.ActivityType.listening, "curhat e soal code review yang kejam"),
    (discord.ActivityType.watching, "environment variable e sing njebrot"),
    (discord.ActivityType.watching, "docker container e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.listening, "curhatan developer e soal fitur yang ga pernah jadi"),
    (discord.ActivityType.watching, "kodinganmu sing ngadat"),
    (discord.ActivityType.playing, "refactor kode e kode warisan jaman dinosaurus"),
    (discord.ActivityType.watching, "bug e sing corrupt"),
    (discord.ActivityType.watching, "frontend e sing ra iso jalan"),
    (discord.ActivityType.playing, "googling error e kode warisan jaman dinosaurus"),
    (discord.ActivityType.watching, "query e sing mlumpat"),
    (discord.ActivityType.listening, "curhatan developer e soal bug sing ra iso fix"),
    (discord.ActivityType.watching, "docker container e sing amblas"),
    (discord.ActivityType.watching, "log e sing kepanasan"),
    (discord.ActivityType.listening, "celotehan e soal deadline besok"),
    (discord.ActivityType.listening, "curhat e sing ra ono entek'e"),
    (discord.ActivityType.playing, "deploy gagal e junior developer polos"),
    (discord.ActivityType.playing, "mikirin solusi buat kode warisan jaman dinosaurus"),
    (discord.ActivityType.watching, "backend e sing nangis"),
    (discord.ActivityType.watching, "pipeline e sing amblas"),
    (discord.ActivityType.watching, "query e sing gak keurus"),
    (discord.ActivityType.playing, "rebuild project e scope creep sing ra kelar-kelar"),
    (discord.ActivityType.playing, "googling error e stack overflow sing koyok kitab suci"),
    (discord.ActivityType.playing, "game tebak deadline besok"),
    (discord.ActivityType.watching, "bug e sing iso opo iki"),
    (discord.ActivityType.playing, "rebuild project e kode warisan jaman dinosaurus"),
    (discord.ActivityType.watching, "git log e sing nangis"),
    (discord.ActivityType.watching, "server e sing corrupt"),
    (discord.ActivityType.listening, "ocehan e soal code review yang kejam"),
    (discord.ActivityType.watching, "query e sing koyok taek"),
    (discord.ActivityType.watching, "API e sing koyok taek"),
    (discord.ActivityType.playing, "debugging client ra karuan"),
    (discord.ActivityType.watching, "kode spaghetti e sing ajaib kok iso jalan"),
    (discord.ActivityType.watching, "server e sing amblas"),
    (discord.ActivityType.playing, "refactor kode e junior developer polos"),
    (discord.ActivityType.watching, "docker container e sing nangis"),
    (discord.ActivityType.watching, "database e sing iso opo iki"),
    (discord.ActivityType.watching, "API e sing mblenyek"),
    (discord.ActivityType.watching, "query e sing iso opo iki"),
    (discord.ActivityType.watching, "konfigurasi e sing ngadat"),
    (discord.ActivityType.watching, "arsitektur e sing iso opo iki"),
    (discord.ActivityType.watching, "API e sing nangis"),
    (discord.ActivityType.listening, "curhat e soal deploy yang gagal terus"),
    (discord.ActivityType.playing, "game tebak stack overflow sing koyok kitab suci"),
    (discord.ActivityType.watching, "kode spaghetti e sing mblenyek"),
    (discord.ActivityType.playing, "permainan kesabaran stack overflow sing koyok kitab suci"),
    (discord.ActivityType.listening, "tangisan e soal bug sing ra iso fix"),
    (discord.ActivityType.playing, "mikirin solusi buat bug production malam ini"),
    (discord.ActivityType.playing, "mainin stack overflow sing koyok kitab suci"),
    (discord.ActivityType.listening, "sambatmu soal gaji yang belum naik"),
    (discord.ActivityType.playing, "permainan kesabaran client ra karuan"),
    (discord.ActivityType.playing, "googling error e client ra karuan"),
    (discord.ActivityType.watching, "arsitektur e sing corrupt"),
    (discord.ActivityType.listening, "celotehan e soal testing yang ga kelar"),
    (discord.ActivityType.watching, "kodinganmu sing corrupt"),
    (discord.ActivityType.watching, "konfigurasi e sing error terus"),
    (discord.ActivityType.watching, "environment variable e sing gak keurus"),
    (discord.ActivityType.playing, "mainin memory leak sing ra ketemu"),
    (discord.ActivityType.watching, "pipeline e sing corrupt"),
    (discord.ActivityType.watching, "database e sing ra iso jalan"),
    (discord.ActivityType.watching, "API e sing corrupt"),
    (discord.ActivityType.playing, "permainan kesabaran requirement sing ganti terus"),
    (discord.ActivityType.listening, "omelan client e sing ra ono entek'e"),
    (discord.ActivityType.watching, "kodinganmu sing nangis"),
    (discord.ActivityType.listening, "celotehan e soal gaji yang belum naik"),
    (discord.ActivityType.watching, "database e sing njebrot"),
    (discord.ActivityType.watching, "git log e sing gak keurus"),
    (discord.ActivityType.watching, "server e sing kepanasan"),
    (discord.ActivityType.watching, "database e sing amblas"),
    (discord.ActivityType.watching, "git log e sing njebrot"),
    (discord.ActivityType.watching, "kodinganmu sing mlumpat"),
    (discord.ActivityType.watching, "kodinganmu sing ra iso jalan"),
    (discord.ActivityType.watching, "database e sing kepanasan"),
    (discord.ActivityType.playing, "game tebak client ra karuan"),
    (discord.ActivityType.watching, "konfigurasi e sing nangis"),
    (discord.ActivityType.watching, "environment variable e sing ngadat"),
    (discord.ActivityType.listening, "keluhan e soal bug sing ra iso fix"),
    (discord.ActivityType.listening, "curhatan developer e soal deploy yang gagal terus"),
    (discord.ActivityType.listening, "omelan client e soal server yang sering down"),
    (discord.ActivityType.listening, "tangisan e soal deploy yang gagal terus"),
    (discord.ActivityType.listening, "tangisan e soal server yang sering down"),
    (discord.ActivityType.listening, "komplen e soal bug sing ra iso fix"),
    (discord.ActivityType.watching, "backend e sing koyok taek"),
    (discord.ActivityType.watching, "pipeline e sing mlumpat"),
    (discord.ActivityType.playing, "mainin requirement sing ganti terus"),
    (discord.ActivityType.watching, "codebase e sing ngadat"),
    (discord.ActivityType.watching, "arsitektur e sing njebrot"),
    (discord.ActivityType.watching, "kodinganmu sing bosok"),
    (discord.ActivityType.watching, "docker container e sing gak keurus"),
    (discord.ActivityType.watching, "log e sing njebrot"),
    (discord.ActivityType.listening, "curhatan developer e sing ra ono entek'e"),
    (discord.ActivityType.playing, "mainin scope creep sing ra kelar-kelar"),
    (discord.ActivityType.watching, "docker container e sing mlumpat"),
    (discord.ActivityType.playing, "rebuild project e client ra karuan"),
    (discord.ActivityType.watching, "server e sing mblenyek"),
    (discord.ActivityType.watching, "server e sing nangis"),
    (discord.ActivityType.listening, "komplen e soal deploy yang gagal terus"),
    (discord.ActivityType.watching, "kode spaghetti e sing modyar"),
    (discord.ActivityType.watching, "git log e sing dipiara-piara tapi tetep rusak"),
    (discord.ActivityType.playing, "simulator ngadepin memory leak sing ra ketemu"),
    (discord.ActivityType.watching, "kode spaghetti e sing bosok"),
    (discord.ActivityType.playing, "simulator ngadepin client ra karuan"),
    (discord.ActivityType.watching, "kode spaghetti e sing error terus"),
    (discord.ActivityType.watching, "backend e sing modyar"),
    (discord.ActivityType.watching, "konfigurasi e sing bosok"),
]

class StatusHandler(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.rotate_status.start()

    def cog_unload(self):
        self.rotate_status.cancel()

    @tasks.loop(minutes=30.0)
    async def rotate_status(self):
        try:
            act_type, msg = random.choice(STATUS_MESSAGES)
            activity = discord.Activity(type=act_type, name=msg)
            await self.bot.change_presence(activity=activity)
        except Exception as e:
            log.error(f"Error rotating status: {e}")

    @rotate_status.before_loop
    async def before_rotate(self):
        await self.bot.wait_until_ready()

async def setup(bot):
    await bot.add_cog(StatusHandler(bot))